name: Mirror

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        run: |
          docker run --rm \
            -e DOCKERHUB_USER=${{ secrets.DOCKERHUB_USERNAME }} \
            -e DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }} \
            -v ./sync.yml:/config/sync.yml:ro \
            regclient/regsync -c /config/sync.yml once
